// Get TimeSlots.
export const LOAD_TIME_SLOTS = 'LOAD_TIME_SLOTS'
export const LOAD_TIME_SLOTS_SUCCESS = 'LOAD_TIME_SLOTS_SUCCESS'
export const LOAD_TIME_SLOTS_FAILURE = 'LOAD_TIME_SLOTS_FAILURE'

// Get Propeties
export const LOAD_PROPERTIES = 'LOAD_PROPERTIES'
export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS'
export const LOAD_PROPERTIES_FAILURE = 'LOAD_PROPERTIES_FAILURE'

// Set the selectedProperty
export const SET_PROPERTY = 'SET_PROPERTY'

// Flash Notifications
export const ADD_FLASH_NOTIFICATION = 'ADD_FLASH_NOTIFICATION';