// Get TimeSlots.
export const LOAD_TIME_SLOTS = 'LOAD_TIME_SLOTS'
export const LOAD_TIME_SLOTS_SUCCESS = 'LOAD_TIME_SLOTS_SUCCESS'
export const LOAD_TIME_SLOTS_FAILURE = 'LOAD_TIME_SLOTS_FAILURE'

// Get Propeties
export const LOAD_PROPERTIES = 'LOAD_PROPERTIES'
export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS'
export const LOAD_PROPERTIES_FAILURE = 'LOAD_PROPERTIES_FAILURE'

// Create new inquiry
export const CREATE_INQUIRY = 'CREATE_INQUIRY'
export const CREATE_INQUIRY_SUCCESS = 'CREATE_INQUIRY_SUCCESS'
export const CREATE_INQUIRY_FAILURE = 'CREATE_INQUIRY_FAILURE'

// Flash Notifications
export const ADD_FLASH_NOTIFICATION = 'ADD_FLASH_NOTIFICATION';

// Set Selected TIme Slot
export const SET_SELECTED_TIME_SLOT = 'SET_SELECTED_TIME_SLOT';